# Generated by Django 5.0.6 on 2024-07-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('status', models.CharField(choices=[('Order placed', 'Order placed'), ('Order Dispatched', 'Order Dispatched'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=50)),
                ('delivery_date', models.DateField()),
            ],
        ),
    ]
